apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels: 
    name: jenkins-service
    app: demo-jenkins
spec:
  type: NodePort
  selector:
    name: jenkins-pod
    app: demo-jenkins
  ports:
    - nodePort: 30008
      port: 8080
      targetPort: 8080