apiVersion: v1
kind: Pod
metadata:
  labels:
    name: app
  name: app
  namespace: elastic-stack
spec:
  containers:
  - image: kodekloud/event-simulator
    imagePullPolicy: Always
    name: app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /log
      name: log-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xxj79
      readOnly: true
  - name: sidecar
    image: kodekloud/filebeat-configured
    volumeMounts:
      - name: log-volume
        mountPath: /var/log/event-simulator/
  restartPolicy: Always
  serviceAccountName: default