apiVersion: v1
kind: Service
metadata:
    name: httpd-service
    labels: 
       name: httpd-service
       app: demo-httpd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
    name: httpd-pod
    app: demo-httpd