apiVersion: v1
kind: Service
metadata:
    name: pet-service
    labels: 
       name: pet-service
       app: demo-pet
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  selector:
    name: pet-pod
    app: demo-pet