apiVersion: v1
kind: Service
metadata:
  name: prom-service
  labels: 
    name: prom-service
    app: demo-prom
spec:
  type: NodePort
  selector:
    name: prom-pod
    app: demo-prom
  ports:
    - nodePort: 30004
      port: 9090
      targetPort: 9090