apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    name: grafana-service
    app: demo-grafana
spec:
  type: NodePort
  selector:
    name: grafana-pod
    app: demo-grafana
  ports:
    - nodePort: 30002
      port: 3000
      targetPort: 3000